---
# playbook.yml
- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
      #  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
#  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'
